index:
    path: /
    controller: App\Controller\IndexController::index

cerad_camper_register:
    path:  /camper/register/{id}
    defaults:
        id: 0
        _controller: App\Controller\CamperRegisterController::register
        _template: 'Camper/Register/CamperRegisterIndex.html.twig'

cerad_camper_payment:
    path:  /camper/payment/{id}
    defaults:
        id: 0
        _controller: App\Controller\CamperPaymentController::payment
        _template: 'Camper/Payment/CamperPaymentIndex.html.twig'

cerad_player_register:
    path:  /player/register/{id}
    defaults:
        id: 0
        _controller: App\Controller\PlayerRegisterController::register
        _template: 'Player/Register/PlayerRegisterIndex.html.twig'

cerad_player_payment:
    path:  /player/payment/{id}
    defaults:
        id: 0
        _controller: App\Controller\PlayerPaymentController::payment
        _template: 'Player/Payment/PlayerPaymentIndex.html.twig'

cerad_player_wanabe_register:
    path:  /player-request/register/{id}
    defaults:
        id: 0
        _controller: App\Controller\PlayerWanabeRegisterController::register
        _template: 'PlayerWanabe/Register/PlayerRegisterIndex.html.twig'

cerad_player_wanabe_confirm:
    path:  /player-confirmation/register/{id}
    defaults:
        id: 0
        _controller: App\Controller\PlayerWanabeConfirmController::confirm
        _template: 'PlayerWanabe/Register/PlayerConfirmIndex.html.twig'

cerad_player_wanabe_list:
    path:  /player-request/list
    defaults:
        _controller: App\Controller\PlayerWanabeListController::list
        _template: 'PlayerWanabe/List/PlayerListIndex.html.twig'
