index:
    path: /
    controller: App\Controller\IndexController::index

cerad_camper_register:
    path:  /camper/register/{id}
    defaults:
        id: 0
        _controller: App\Controller\CamperRegisterController::register
        _template: 'Camper/Register/CamperRegisterIndex.html.twig'

cerad_camper_payment:
    path:  /camper/payment/{id}
    defaults:
        id: 0
        _controller: App\Controller\CamperPaymentController::payment
        _template: 'Camper/Payment/CamperPaymentIndex.html.twig'

cerad_player_register:
    path:  /player/register/{id}
    defaults:
        id: 0
        _controller: App\Controller\PlayerRegisterController::register
        _template: 'Player/Register/PlayerRegisterIndex.html.twig'

cerad_player_payment:
    path:  /player/payment/{id}
    defaults:
        id: 0
        _controller: App\Controller\PlayerPaymentController::payment
        _template: 'Player/Payment/PlayerPaymentIndex.html.twig'
